---
title: 'Mini Project #3'
author: "Mae Rosenstein, Talia Seshaiah and Olivia Baldwin"
date: "4/15/2018"
output: 
  html_document: 
    code_folding: hide
    df_print: paged
---
```{r warning = FALSE}
library(tidyverse)
library(macleish)
library(lubridate)
library(dplyr)
load("maple_sap.rda")
library(sf) # done and done
library(devtools)
library(leaflet)
```

```{r warning = FALSE}
# Live weather data 
mac <- etl("macleish") %>%
 etl_update()
whately <- mac %>%
 tbl("whately") %>%
 collect(n = Inf)
```


```{r warning = FALSE}
# Selecting important parts of weather data
weather_info <- whately %>%
  select(when, temperature, pressure)

glimpse(weather_info)

# Changing the date format of the weather_info dataset 
weather_info2 <- whately %>%
mutate(date2 = as_date(when)) 
glimpse(weather_info2)
```

```{r warning = FALSE}
# Changing the date format of the weather_info dataset 
# date <- formatdate(yyyy-mm-dd)
# as.interval(date, ymd())
# glimpse(weather_info)

# Joining pressure and tempature from weather data with maple sap data
 maple_sap_select <- maple_sap %>% 
  select(when, sap) 
  View(maple_sap_select)

weather_info_select <- weather_info2 %>%
  select(date2, temperature, pressure) %>%
  rename(when = date2) 
View(weather_info_select)

full_dataset <- full_join(maple_sap_select, weather_info_select, by = "when", copy = TRUE)

View(full_dataset)
temp_data <- full_dataset %>%
  group_by(when) %>%
  summarise(high = max(temperature),
           low = min(temperature),
           sap = max(sap)) %>%
  filter(!is.na(sap))

ggplot(temp_data, aes(x = when)) +
  geom_line(aes(y = low), position = "jitter", color = "blue") +
  geom_line(aes(y = high), position = "jitter", color = "red") +
  labs(title = "Temperature vs Time during the mapling season",
       x = "Mapling Seasons, 2013-2017",
       y = "Temperature (degrees Fahrenheit)",
       caption = "Source: whately weather package")
ggplot(temp_data, aes(x = when)) +
  geom_bar(aes(y = sap), stat = "identity", position = position_dodge(), color = "#996600") +
  labs(title = "Sap vs Time during the mapling season",
       x = "Mapling Seasons, 2013-2017",
       y = "Sap collection (gallons)",
       caption = "Source: maple sap data, macleish package")
  

```

```{r warning = FALSE}
mass_data <- tribble(
  ~year, ~yield_per_tap, ~production, ~opener, ~closer, ~season_length,
  2015, 0.242, 75000, 2015-03-14, 2015-04-11, 28,
  2016, 0.244, 77000, 2016-01-13, 2016-04-20, 32,
  2017, 0.263, 84000, 2017-01-10, 2017-04-13, 42
)
mass_data <- as.data.frame(mass_data)

ggplot(mass_data, aes(x = year, y = season_length)) +
  geom_bar(aes(y = season_length, fill = yield_per_tap), stat = "identity", position = position_dodge()) +
  labs(title = "Season Length vs Time during the mapling season",
       x = "Mapling Seasons, 2013-2017",
       y = "Season Length (days)",
       caption = "Source: United States Maple Syrup Production, National Agricultural Statistics Service") +
  scale_fill_continuous(low = "#996600", high = "#663300", name = "Yield per tap\n(gallons/number of taps)")

```

## Local sugarhouses and sugaring stations
```{r warning = FALSE}
library(sf)
library(leaflet)


#creating a leaflet map with the other sugar houses

my_points <- tribble(
  ~point, ~lat, ~lon, ~geometry,
  "Dufresne's Sugarhouse", 42.415240, -72.761856, "POINT",
  "Brookledge Sugarhouse", 42.428837, -72.662263, "POINT",
  "North Hadley Sugar Shack", 42.379097, -72.584417,"POINT",
  "Zawalick's Sugar House", 42.327841, -72.721173, "POINT", 
  "Hanging Mountain Farm", 42.323968, -72.754591, "POINT", 
  "Steve's Sugar Shack", 42.307773, -72.771403, "POINT",
  "Mayval Farm", 42.300522, -72.744081, "POINT"
)

leaflet() %>%
  addTiles() %>%
  addMarkers(data = my_points, popup = ~point)

```

















## MacLeish Property with attention to its forests.
```{r warning = FALSE}
#macleish map with forests and landmarks

macmac <- data.frame(lat = 42.45885, lon = -72.68725)
macmac_plot <- leaflet() %>%
  addTiles() %>%
  addMarkers(lng = ~lon, lat = ~lat, data = macmac,
             popup = "Macleish Property (Buildings, Streams and Trails)") %>%
  addPolygons(data = macleish_layers[["forests"]],
              weight = 1, popup = ~Sheet1__Na) %>%
  addMarkers(data = macleish_layers[["landmarks"]],
             popup = ~Label)
macmac_plot

```

[^1]: GitHub repository

[^https://github.com/mrosenstein/mp3]
